careers/urls.py
from django.urls import path
from .views import apply_view, careers_page

urlpatterns = [
    path('', careers_page, name='careers'),
    path('<int:pk>/', apply_view, name='apply'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #Django Admin
    path('ops-control/', admin.site.urls),

    #User Management
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    #Local Apps
    path('', include('pages.urls')),
    path('careers/', include('careers.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('news/', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from news.views import news_view, article_view, load_articles

urlpatterns = [
    path('', news_view, name='news'),
    path('<int:pk>', article_view, name="article"),
    path('load-articles', load_articles, name="load_articles"),
    ]

careers/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator
from accounts.models import CustomUser
from django.contrib.auth import get_user_model
from multiselectfield import MultiSelectField

import datetime
from datetime import timedelta


#Model for the information behind a particular job listing
class Career(models.Model):
    job_title = models.CharField(max_length=200)
    job_summary = models.CharField(max_length=500)
    job_description = models.CharField(max_length=2000)
    rate_of_pay = models.DecimalField(max_digits=6, decimal_places=2)
    job_location = models.CharField(max_length=100)
    job_number_of_positions = models.IntegerField(MinValueValidator(1), default=1)
    TODAY = datetime.date.today()
    FORTNIGHT = timedelta(days=14)
    DEF_APPLY_DATE = (TODAY + FORTNIGHT).strftime("%d/%m/%y")
    TODAY_STRING = TODAY.strftime("%d/%m/%y")
    job_apply_by_date = models.CharField(max_length=12, default=DEF_APPLY_DATE)
    job_date_posted = models.CharField(max_length=12, default=TODAY_STRING, editable=False)
    job_posted_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    job_average_weekly_hours = models.IntegerField(default=45)

    CONTRACT_TYPE_CHOICES = [
        ('FT_T', 'Full time - Temporary'),
        ('FT_P', 'Full time - Permanent'),
        ('PT_T', 'Part time - Temporary'),
        ('PT_P', 'Part time - Permanent'),
    ]
    job_contract_type = models.CharField(
        max_length=30,
        choices = CONTRACT_TYPE_CHOICES,
        default = 'PT_T')

    JOB_TYPE_CHOICES = [
        ('REC', 'Receptionist'),
        ('SG', 'Security Guard'),
        ('RVRCOP', 'Control Room Operator'),
        ('CO','Cleaning Operative'),
        ('MD','Mobile Driver'),
        ('MS','Mobile Supervisor'),
        ('OPS','Operations Manager')
    ]
    job_type = models.CharField(
        max_length=30,
        choices = JOB_TYPE_CHOICES,
        default = 'SG')
    vetting_required = models.BooleanField(default=False)
    number_of_applications = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.job_title

    def get_absolute_url(self):
        return reverse('vacancy')

#Model for the application form, collecting all applicant information (pre-vetting) for initial screening purposes.
class JobApplication(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email_address = models.EmailField(max_length=100)
    mobile_number = models.CharField(max_length=11)
    first_line = models.CharField(max_length=100, help_text="First Line of Address")
    second_line = models.CharField(max_length=100, blank=True, help_text="Second Line of Address")
    town = models.CharField(max_length=100)
    county = models.CharField(max_length=100)
    postcode = models.CharField(max_length=7)
    uk_bank_account = models.BooleanField(default=False)
    criminal_offences = models.BooleanField(default=False)
    over_18 = models.BooleanField(default=False)
    job_reference = models.ForeignKey(Career, on_delete=models.CASCADE, related_name='application')
    address_history = models.BooleanField(default=False)
    sia_badge = models.BooleanField(default=False)

    SIA_BADGE_TYPES = [
        ('DS', 'Door Supervisor'),
        ('CCTV', 'CCTV'),
        ('CP', 'Close Protection'),
        ('SG', 'Security Guarding'),
        ('VI', 'Vehicle Immobiliser'),
    ]

    sia_badges = MultiSelectField(
        max_length=100,
        choices=SIA_BADGE_TYPES,
        blank=True,
    )

    working_history = models.BooleanField(default=False)
    right_to_work = models.BooleanField(default=False)

    GROUP_A_CHOICES = [
        ('SVP', 'Signed Valid Passport'),
        ('UKBC', 'UK Birth Certificate'),
        ('UKDL', 'UK Driving License'),
        ('EUID', 'Valid EU ID Card'),
        ('UKFA', 'Valid UK Firearms License')
    ]
    group_a = MultiSelectField(
        max_length=300, 
        choices=GROUP_A_CHOICES,
        default='')

    GROUP_B_CHOICES = [
        ('MC', 'Marriage Certificate'),
        ('BNC', 'British National Certificate'),
        ('P45', 'P45**'),
        ('VBWP', 'Visa or British Work Certificate'),
        ('P60', 'P60**'),
        ('DWP', 'Letter from DWP'),
        ('BS', 'Bank Statement*'),
        ('CCS', 'Credit Card Statement*'),
        ('MS', 'Mortgage Statement**'),
        ('CS', 'Court Summons**'),
        ('UB', 'Utility Bill*'),
        ('CBL', 'Child Benefit Letter**'),
        ('TVL', 'TV License**'),
        ('PSAL', 'Pay Slip'),
        ('PS', 'Pension Statment'),
        ('CUKBC', 'Copy of UK Birth Certificate')
    ]
    group_b = MultiSelectField(
        max_length=300,
        choices=GROUP_B_CHOICES,
        default='')

    cv = models.FileField(upload_to='cv/', blank=True)

    class Result(models.IntegerChoices):
        UNDECIDED=0, 'Undecided'
        SUCCESS=1, 'Success'
        FAIL=2, 'Fail'
    result = models.SmallIntegerField(
        choices=Result.choices,
        default=Result.UNDECIDED,
    )

    def __str__(self):
        return str(self.id)

#Model to collect the data for those interested in taking training with us so that they can be contacted when appropriate
class TrainingInterest(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    COURSE_CHOICES = [
        ("siatu", "SIA Top Up Training"),
        ("ds", "Door Supervisor Course"),
        ("first aid", "First Aid"),
        ("cctv", "CCTV Operator Course"),
        ("guarding", "Security Guarding Course"),
        ("cleaning", "BICS Cleaning Course"),
        ("reception", "Receptionist Practice and Professionalism"),
        ("ct", "Counter Terrorism")
    ]

    course = models.CharField(
        max_length=70,
        choices= COURSE_CHOICES,
        help_text = "Which course interests you most?"
        )

    def __str__(self):
        return str(self.email)

careers/views.py
from django.shortcuts import render, redirect
from .models import Career, JobApplication
from accounts.models import CustomUser
from careers.forms import ApplicationForm, TrainingInterestForm
from django.http import HttpResponse, JsonResponse
from django.template.context_processors import csrf
from crispy_forms.utils import render_crispy_form


#Function based view for the rendering of the careers page and the training interest form at the foot of the page, data from form
#submitted via ajax to database, some control in between in JS.
def careers_page(request):
    form = TrainingInterestForm(request.POST or None)
    model = Career
    careers = model.objects.all()
    context = {
        'careers' : careers,
        'form' : form,
    }
    data = {}
    if request.is_ajax():
        if form.is_valid():
            form.save()
            data['success'] = True
            data['name'] = form.cleaned_data['name']
            return JsonResponse(data)
        else:
            data['success'] = False
    else:       
        return render(request, 'careers/careers.html', context)


#Funciton based view for the application form page, submitting the application form to the database through AJAX, checking
#for form validation
def apply_view(request, pk):
    context = {}
    career = Career.objects.get(id = pk)
    context['career'] = career
    form = ApplicationForm(request.POST or None, request.FILES or None)
    data = {}
    if request.is_ajax():
        if form.is_valid():
            application = form.save(commit=False)
            application.job_reference = Career.objects.get(pk=pk)
            application = application.save()
            job_reference = Career.objects.get(pk=pk)
            job_reference.number_of_applications += 1
            job_reference.save()
            data['success'] = True
            return JsonResponse(data)
        else:
            data = {}
            data['success'] = False
            ctx = {}
            ctx.update(csrf(request))
            form_html = render_crispy_form(form, context=ctx)
            data['form_html'] = form_html
            return JsonResponse(data)
    else:
        context['form'] = form
        return render(request, "careers/apply.html", context)

templates/careers/apply.html
{% extends '_sisterbase.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="contianer-fluid apply-header">
    <div class="apply-header-image">
        <img src="{% static 'images/portallogo.jpg' %}" alt="apply-header-image" class="apply-image image-darken">
    </div>
    <div class="apply-header-text">
        <h1 class="apply-text">Find out more and apply for the {{ career.job_title }} job with Samson.</h1>
    </div>
</div>

<div class="container-fluid career-detail">
    <div class="row justify-content-around">
        <div class="col-12 col-sm-12 col-md-6 detail-col">
            <div class="detail-con">
                <div class="detail-title">
                    <h5>The Details</h5>
                </div>
                <div class="c-detail-text">
                    <h5>{{ career.job_title }}</h5>
                    <p>Job Summary: {{ career.job_summary }}</p>
                    <p>Job Description: {{ career.job_description }}</p>
                    <p>Rate of Pay:{{ career.rate_of_pay}}</p>
                    <p>Location: {{ career.job_location }}</p>
                    <p>Average Weekly Hours:{{ job_average_weekly_hours }}</p>
                    <p>Number of Positions Available: {{ career.job_number_of_positions }}</p>
                    <p>Apply By:{{ job_apply_by_date }}</p>
                    <p>Date Posted: {{ job_date_posted }}</p>
                </div>
            </div>
            
        </div>
        <div class="col-12 col-sm-12 col-md-6 training-col">
            <div class="training-con">
                <div class="c-training-title">
                    <h5>Additonal Information</h5>
                </div>
                <div class="c-training-text">
                    <h5>{{ career.job_title }}</h5>
                    <p>Some info about training and maybe need to know information/disclaimers about application and vetting</p>
                    <p>Samson aim to accomodate our staff as best as possible, when you begin your career wiht us you will be expected
                        to improve upon your skills by using our online training programs, accessing our training centre and working with other skilled
                        security practitioners.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    {% crispy form %}
</div>

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 application-submitted">
            <h3>Your Application was successfully submitted, thank you for applying, we will call to arrange an interview if your application is successful.</h3>
        </div>
        <div class="col-12 application-failed">
            <h3>Your Application failed to submit, please check above.</h3>
        </div>
    </div>
</div>

{% endblock content %}

templates/careers/careers.html
{% extends '_sisterbase.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container-fluid career-hero">
    <div class="row">
        <img src="{% static 'images/Compressed/Photo_15_Compressed.jpg' %}" class="career-hero-image image-darken">
        <h1 class="career-hero-text"> Careers at Samson </h1>
    </div>
</div>

<div class="container-fluid careers-header">
    <div class="row justify-content-around">
        <div class="col-6 career-side">
            <div class="career-title">
                <h1>Careers</h1>
                <a href="#vacancies" class="btn btn-lg btn-primary">See Vacancies</a>
            </div>
            <div class="career-content">
                <div class="career-section" id="careerSamson">
                    <div class="careerimage">
                        <img src="{% static 'images/portallogo.jpg' %}" alt="">
                    </div>
                    <div class="careertext text-center">
                        <h4>Working at Samson</h4>
                        <div class="underline"></div>
                        <p>Working in Facilities Management can be rewarding and very challenging, every task is different
                            and we need to be adaptable at all times to provide the right service at the right times and often
                            at short notice, if you like being kept on your toes, this is the right industry for you.
                        </p>
                    </div>
                </div>
                <div class="career-section" id="careerSamson">
                    <div class="careerimage">
                        <img src="{% static 'images/Compressed/Photo_31_Compressed.jpg' %}" alt="">
                    </div>
                    <div class="careertext text-center">
                        <h4>Facilites management</h4>
                        <div class="underline"></div>
                        <p>Facilities management covers a wide range of services. Samson made their start in security but
                            expanded in to reception, cleaning, landscaping and other unique services related to the specific
                            needs of the client on the day. We need multiskilled and committed staff to help us adapt to the challenges
                            that are presented to us as an FM organisation.
                        </p>
                    </div>
                </div>
                <div class="career-section" id="careerSamson">
                    <div class="careerimage">
                        <img src="{% static 'images/Compressed/Photo_34_Compressed.jpg' %}" alt="">
                    </div>
                    <div class="careertext text-center">
                        <h4>Adaptability</h4>
                        <div class="underline"></div>
                        <p>Here at Samson we do the best we can to push those who have the drive and the talent up through the ranks,
                            as a company who are always on the lookout for talent and new growth opportunities, we give those willing to
                            help us the best chance possible to do so.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6 training-side">
            <div class="training-title">
                <h1>Training</h1>
                <a href="#training" class="btn btn-lg btn-danger">Opportunities</a>
            </div>
            <div class="career-content">
                <div class="career-section" id="careerSamson">
                    <div class="careerimage">
                        <img src="{% static 'images/Compressed/Photo_41_Compressed.jpg' %}" alt="">
                    </div>
                    <div class="careertext text-center">
                        <h4>Why do training?</h4>
                        <div class="underline"></div>
                        <p>Receiving quality training from a company like Samson gives you the qualifications necessary
                            to stand out in your specialisation. Learning leads to better job opportunities and the best
                            chance of advancement through the industry.
                        </p>
                    </div>
                </div>
                <div class="career-section" id="careerSamson">
                    <div class="careerimage">
                        <img src="{% static 'images/Compressed/Photo_2_Compressed.jpg' %}" alt="">
                    </div>
                    <div class="careertext text-center">
                        <h4>What can we offer ?</h4>
                        <div class="underline"></div>
                        <p>We provide courses in the major areas of Facilites Management. Security and every facet of
                            it, primarily focused on one of the most challenging environments to operate within, Health care.
                            We also train professional cleaners, receptionists and engineers.
                        </p>
                    </div>
                </div>
                <div class="career-section" id="careerSamson">
                    <div class="careerimage">
                        <img src="{% static 'images/Compressed/Photo_26_Compressed.jpg' %}" alt="">
                    </div>
                    <div class="careertext text-center">
                        <h4>When is the right time to train ?</h4>
                        <div class="underline"></div>
                        <p>We suggest receiving the training for your desired role before applying for jobs,
                            this will uniquely position you above competition to secure roles and be recommended
                            for advancement through management.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="career-block container-fluid mb-5 px-5 text-center" id="vacancies">
    <h1 class="career-block-title">Current Vacancies</h1>
    <div class="underline"></div>
    <table class="table table-striped table-hover vacancies-table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Summary</th>
                <th scope="col">Description</th>
                <th scope="col">Rate</th>
                <th scope="col">Average Weekly Hours</th>
                <th scope="col">Contract Type</th>
                <th scope="col">Location</th>
                <th scope="col">Number of Positions</th>
            </tr>
        </thead>
        <tbody>
            {% comment %} for the interative rendering of individual vacancies inside this table {% endcomment %}
            {% for career in careers %}
                <tr>
                    <td>{{ career.job_title }}</td>
                    <td>{{ career.job_summary }}</td>
                    <td>{{ career.job_description }}</td>
                    <td>{{ career.rate_of_pay }}</td>
                    <td>{{ career.job_average_weekly_hours }}</td>
                    <td>{{ career.get_job_contract_type_display }}</td>
                    <td>{{ career.job_location }}</td>
                    <td>{{ career.job_number_of_positions }}</td>
                    <td><a href="{% url 'apply' career.pk %}" class="btn btn-sm btn-primary">Apply</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% comment %} mobile only vacancies rendering {% endcomment %}
<div class="mob-career-block container-fluid mb-5 mt-5 text-center" id="vacancies">
    <h1 class="career-block-title">Current Vacancies</h1>
    <div class="underline"></div>
    <table class="table table-striped table-hover vacancies-table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Rate p/h</th>
                <th scope="col">Hours p/w</th>
                <th scope="col">Location</th>
            </tr>
        </thead>
        <tbody>
            {% for career in careers %}
                <tr>
                    <td>{{ career.job_title }}</td>
                    <td>{{ career.rate_of_pay }}</td>
                    <td>{{ career.job_average_weekly_hours }}</td>
                    <td>{{ career.job_location }}</td>
                    <td><a href="{% url 'apply' career.pk %}" class="btn btn-sm btn-primary">Apply</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% comment %} where the training request form lives at the bottom of the page {% endcomment %}
<div class="training-block container-fluid pt-5" id="training">
    <div class="row">
        <h1 class="training-block-title">Training</h1>
        <div class="training-underline mb-5"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-6">
            <div class="col-12 training-text text-center">
                <h3>New training centre under construction</h3>
                <div class="underline mb-3"></div>
                <p>Our new specialist training facility is almost finished construction in Wavertree. With new technology, a suite of tools for training, expert trainers and career progression pathways available
                    please complete the form below to register your interest and we will contact you with more information upon completion.
                </p>
            </div>
            <div class="col-12">
                {% crispy form %}
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6">
            <img src="{% static 'images/Compressed/Photo_17_Compressed.jpg' %}" alt="" class="training-img">
        </div>
    </div>
</div>

{% endblock content %}